# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 3) do

  create_table "participants", :force => true do |t|
    t.string   "name"
    t.integer  "prize_id"
    t.integer  "raffle_id"
    t.string   "email"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "prizes", :force => true do |t|
    t.string   "name"
    t.float    "value"
    t.string   "description"
    t.integer  "raffle_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "raffles", :force => true do |t|
    t.string   "name"
    t.boolean  "closed"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

end
